name = "lunaroracle"
main = "src/index.ts"
compatibility_date = "2024-08-11"

[env.development]
vars = { ENVIRONMENT = "development" }

[env.production]
vars = { ENVIRONMENT = "production" }

# Database configuration (we'll connect to existing lunarcrush-universal-db)
[[d1_databases]]
binding = "DB"
database_name = "lunarcrush-universal-db"
database_id = "" # We'll need to get this from Cloudflare dashboard

# KV namespace for caching
[[kv_namespaces]]
binding = "CACHE"
id = "" # We'll set this up later
preview_id = ""
